feature/add sort to admin page
glencbz/call-home pull request #23
Opened 2020-11-23 07:31 UTC by fabianchua6

Add sort to admin page and tidied up the UI

2020-11-24 12:07 UTC, glencbz requested changes
Be sure to leave some screenshots so that people can comment :)

2020-11-24 12:07 UTC, glencbz commented on frontend/src/scenes/AdminPage.tsx
> +    rows.push({
Avoid pushing to arrays, that's what the return value of the mapping function is for.

2020-11-24 12:07 UTC, glencbz commented on frontend/src/scenes/AdminPage.tsx
> +      renderCell(row) {
Any reason why this isn't an arrow function?

2020-11-24 12:07 UTC, glencbz commented on frontend/src/scenes/AdminPage.tsx
> +    id: any;
Try defining the row's type as an Interface and avoiding the use of `any` where possible.

2020-11-24 12:07 UTC, glencbz commented on frontend/src/scenes/AdminPage.tsx
> +  allowlistEntries.map((allowlistEntry: any) =>
Try defining an interface for AllowlistEntry. It would be best to put it in a `services/` file, but it would be ok in this file too.

2020-11-25 12:51 UTC, glencbz requested changes
Looks pretty good. Remember to attach some screenshots so that everyone can visualise the changes

2020-11-26 09:45 UTC, fabianchua6 reviewed
![screenshot_2020-11-15_at_10 06 36_pm_720](https://user-images.githubusercontent.com/57614749/100334774-2ba7ec00-300f-11eb-9783-04121ec8bfcc.png)
<img width="1439" alt="screenshot_2020-11-15_at_10 07 22_pm" src="https://user-images.githubusercontent.com/57614749/100334778-2e0a4600-300f-11eb-8e28-e0ed33c13c52.png">

2020-11-26 10:15 UTC, fabianchua6 reviewed
Reviewed and tidied up

2020-11-29 03:53 UTC, glencbz commented
Looks like there are some pretty strange merge conflicts, could you update your branch and PR again?

2020-11-30 03:50 UTC, fabianchua6 commented
> Looks like there are some pretty strange merge conflicts, could you update your branch and PR again?

Ok I tried resolving them, if it doesn't work again, I will pull a fresh copy and open another PR. 👍

2020-12-01 13:06 UTC, glencbz commented on frontend/src/scenes/AdminPage.tsx
> +      renderCell(row) {
Interesting, I'll take a closer look later..

2020-12-01 13:09 UTC, glencbz reviewed
Changes look pretty good! I really want to merge this and I realise that I'm introducing a lot of the merge conflicts. If you're ok with it, I can resolve the merge conflicts on my own end. Otherwise, I think we can schedule a session to work out the conflicts.

2020-12-01 14:18 UTC, fabianchua6 commented
> Changes look pretty good! I really want to merge this and I realise that I'm introducing a lot of the merge conflicts. If you're ok with it, I can resolve the merge conflicts on my own end. Otherwise, I think we can schedule a session to work out the conflicts.

Yes please, I'm gonna have merge conflict PTSD sooner or later 🤣😭

2020-12-07 13:02 UTC, glencbz commented
Manually resolved the merge conflicts using the contents of this PR. Thanks so much @fabianchua6!!

2020-12-07 13:02 UTC, closed without merging