fix/contact page formats
glencbz/call-home pull request #33
Opened 2020-12-13 16:04 UTC by fabianchua6

Fixed formatting of long names in contact list and rounded contact box to match the MVP in figma.
![contacts_before_after](https://user-images.githubusercontent.com/57614749/102017111-d3f3d980-3d9f-11eb-8f98-322343d523b1.png)

2020-12-15 05:31 UTC, fabianchua6 commented
re: commit bf295ea
before:
![bf295ea_Before](https://user-images.githubusercontent.com/57614749/102175067-c6db0580-3ed9-11eb-9e0a-00354d0cd7ab.png)
after:
![bf295ea_After](https://user-images.githubusercontent.com/57614749/102175095-d0646d80-3ed9-11eb-9454-020c1922b709.png)

2020-12-19 04:02 UTC, glencbz approved these changes

2020-12-19 04:05 UTC, glencbz requested changes
Looks good! Handle the min height and it should be good to merge

2020-12-19 04:05 UTC, glencbz commented on frontend/src/scenes/ContactsPage.tsx
> -                    height: '4em',
Use a minHeight so that it looks consistent on smaller entries

2021-01-04 03:51 UTC, glencbz approved these changes

2021-07-28 09:18 UTC, closed without merging